musicstore/Models/AlbumViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace musicstore.Models;

public class AlbumViewModel
{
    [Display(Name = "AlbumName")]
    [Required(ErrorMessage = "{0} is a required field")] 
    public string AlbumName { get; set; }

    [Display(Name = "ArtistName")]
    [Required(ErrorMessage = "{0} is a required field")] 
    public string ArtistName { get; set; }
    
    [Display(Name = "Description")]
    [Required(ErrorMessage = "{0} is a required field")] 
    public string Description { get; set; }

    [Display(Name = "Price")]
    [Range(0, 19.00, ErrorMessage = "{0} must be a number between {1} and {2}")] 
    public decimal Price { get; set; }
}

musicstore/Controllers/CultureController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace musicstore.Controllers;
public class CultureController : Controller
{
    [HttpPost]
    public IActionResult SetCulture(string culture, string returnUrl)
    {
        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions { Expires = DateTimeOffset.UtcNow.AddDays(30) }
        );
        return LocalRedirect(returnUrl);
    }
}

musicstore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using musicstore.Models;

namespace musicstore.Controllers;

public class HomeController(ILogger<HomeController> logger, IHtmlLocalizer<HomeController> localizer)
    : Controller
{
    private readonly ILogger<HomeController> _logger = logger;
    private readonly IHtmlLocalizer<HomeController> _localizer = localizer;

    public IActionResult Index()
    {
        ViewData["Title"] = _localizer["Title"];
        ViewData["Home"] = _localizer["Home"];
        ViewData["About"] = _localizer["About"];
        ViewData["Featured"] = _localizer["Featured"];
        ViewData["Album1Name"] = _localizer["Album1Name"];
        ViewData["Album1Descr"] = _localizer["Album1Descr"];
        ViewData["Album2Name"] = _localizer["Album2Name"];
        ViewData["Album2Descr"] = _localizer["Album2Descr"];
        ViewData["Album3Name"] = _localizer["Album3Name"];
        ViewData["Album3Descr"] = _localizer["Album3Descr"];
        ViewData["Album4Name"] = _localizer["Album4Name"];
        ViewData["Album4Descr"] = _localizer["Album4Descr"];
        ViewData["Album5Name"] = _localizer["Album5Name"];
        ViewData["Album5Descr"] = _localizer["Album5Descr"];
        ViewData["Album6Name"] = _localizer["Album6Name"];
        ViewData["Album6Descr"] = _localizer["Album6Descr"];
        return View();
    }

    public IActionResult About()
    {
        ViewData["Title"] = _localizer["Title"];
        ViewData["Home"] = _localizer["Home"];
        ViewData["About"] = _localizer["About"];
        ViewData["AboutUs"] = _localizer["AboutUs"];
        return View();
    }
    
    public IActionResult LocalizedView()
    {
        return View();
    }

    public IActionResult DataAnnotationView([FromQuery] string? culture)
    {
        ViewData["culture"] = culture;
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DataAnnotationView(AlbumViewModel personViewModel, [FromQuery] string? culture)
    {
        ViewData["culture"] = culture;

        if (!ModelState.IsValid)
        {
            return View();
        }

        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

musicstore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<br />
<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @ViewData["About"]
            </h1>
        </div>
    </div>
    <!-- /.row -->
    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12">
            <p>
                @ViewData["AboutUs"]
            </p>
        </div>
    </div>
    <!-- /.row -->
</div>

musicstore/Views/Home/DataAnnotationView.cshtml
@model AlbumViewModel
@{
    ViewData["Title"] = "Data Annotations";
}

<div class="card w-50">
    <div class="card-body">
        <form asp-action="DataAnnotationView" asp-route-culture=@ViewData["culture"]>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="AlbumName" class="lable-control"></label>
                        <input asp-for="AlbumName" class="form-control"/>
                        <span asp-validation-for="AlbumName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="ArtistName" class="lable-control"></label>
                        <input asp-for="ArtistName" class="form-control"/>
                        <span asp-validation-for="ArtistName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Description" class="lable-control"></label>
                        <input asp-for="Description" class="form-control"/>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Price" class="lable-control"></label>
                        <input asp-for="Price" class="form-control"/>
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary rounded-0 mt-2">Submit</button>
            </div>
        </form>
    </div>
</div>

musicstore/Views/Home/LocalizedView.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@{
    ViewData["Title"] = "IViewLocalizer";
}

@inject IViewLocalizer ViewLocalizer

<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <h1 class="my-4">@ViewLocalizer["Featured"]</h1>
        </div>
        <!-- /.col-lg-3 -->
        <div class="col-lg-9">
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="~/images/36088213154_309743b74f_k.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/images/7161626248_739052058e_k.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/images/8380957206_23bb62bdbd_b.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top" src="~/images/Album1_700x400.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Ken Freeman</a>
                            </h4>
                            <h3 class="card-title">
                                <a href="#">@ViewLocalizer["Album1Name"]</a>
                            </h3>
                            <h5>$9.99</h5>
                            <p class="card-text">@ViewLocalizer["Album1Descr"]</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9734; &#9734; &#9734;</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top" src="~/images/Album2_700x400.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Billy Morgan</a>
                            </h4>
                            <h3 class="card-title">
                                <a href="#">@ViewLocalizer["Album2Name"]</a>
                            </h3>
                            <h5>$10.99</h5>
                            <p class="card-text">@ViewLocalizer["Album2Descr"]</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9734; &#9734;</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top" src="~/images/Album3_700x400.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Iragberi</a>
                            </h4>
                            <h3 class="card-title">
                                <a href="#">@ViewLocalizer["Album3Name"]</a>
                            </h3>
                            <h5>$14.99</h5>
                            <p class="card-text">@ViewLocalizer["Album3Descr"]</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9733;</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top" src="~/images/Album4_700x400.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">James Flint</a>
                            </h4>
                            <h3 class="card-title">
                                <a href="#">@ViewLocalizer["Album4Name"]</a>
                            </h3>
                            <h5>$7.99</h5>
                            <p class="card-text">@ViewLocalizer["Album4Descr"]</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9734; &#9734; &#9734;</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top" src="~/images/Album5_700x400.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Nillu Rat</a>
                            </h4>
                            <h3 class="card-title">
                                <a href="#">@ViewLocalizer["Album5Name"]</a>
                            </h3>
                            <h5>$8.99</h5>
                            <p class="card-text">@ViewLocalizer["Album5Descr"]</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top" src="~/images/Album6_700x400.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Oroukayo</a>
                            </h4>
                            <h3 class="card-title">
                                <a href="#">@ViewLocalizer["Album6Name"]</a>
                            </h3>
                            <h5>$9.99</h5>
                            <p class="card-text">@ViewLocalizer["Album6Descr"]</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9734; &#9734;</small>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->

musicstore/Views/Shared/_CulturePartial.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options

@inject IOptions<RequestLocalizationOptions> LocalizationOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();

    var cultureItems = LocalizationOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.Name })
        .ToList();

    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div>
    <form asp-controller="Culture" asp-action="SetCulture" asp-route-returnUrl="@returnUrl" class="form-horizontal nav-link text-dark">
        <select name="culture" 
                onchange="this.form.submit();" 
                asp-for="@requestCulture.RequestCulture.UICulture.Name" 
                asp-items="cultureItems">
        </select>
    </form>
</div>

musicstore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - musicstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/musicstore.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    @inject IViewLocalizer ViewLocalizer
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">musicstore</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="DataAnnotationView">DataAnnotation</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="LocalizedView">LocalizedView</a>
                    </li>
                    <li class="nav-item">
                        @await Html.PartialAsync("_CulturePartial")
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Chinook Music Store - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>